from flask import Flask,render_template,request
import json
 
app = Flask(__name__)
 
logo_img = 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Facebook_f_logo_%282019%29.svg/1200px-Facebook_f_logo_%282019%29.svg.png' #'https://i.pravatar.cc/100'
userdata = {'user_pagetitle':"Page Title", 
            'user_fullname':"A student @24679",
            'avatar_img': 'https://i.pravatar.cc/151',
            'stories': [
                {'id' : 1, 
                 'message':'story a', 
                 'bg_img': 'https://picsum.photos/600/301',
                 'avatar_img': 'https://i.pravatar.cc/150',
                },
                {'id' : 2, 
                 'message':'story b', 
                 'bg_img': 'https://picsum.photos/600/302',
                 'avatar_img': 'https://i.pravatar.cc/149',                    
                }
            ],
            'posts': [ 
                { "id" : 1, 
                  "user_fullname" : "Mansur" ,
                  'avatar_img': 'https://i.pravatar.cc/152',
                  "timestamp" : "22 October 2021 at 20:30",
                  "message" : "Text content for the post. All images here are randomly generated by picsum.photos or pravatar.cc",
                  "has_img" : True,
                  "post_img": 'https://picsum.photos/401/300',
                  "has_comments": True,
                  "comments" : [
                     {
                      "id": 1,
                      "user_fullname": "A friend",
                      "time_ago": "14h",
                      'avatar_img': 'https://i.pravatar.cc/153',
                      "message":  "This is a comment"
                     },
                     {
                      "id": 2,
                      "user_fullname": "Another friend",
                      "time_ago": "12h",
                      'avatar_img': 'https://i.pravatar.cc/148',
                      "message":  "This is another comment"
                     },
                     
                   ],
                },
                { "id" : 2, 
                  "user_fullname" : "Random person" ,
                  'avatar_img': 'https://i.pravatar.cc/155',                 
                  "timestamp" : "22 October 2021 at 20:29",
                  "message" : "Post without image",
                  "has_img" : False,
                  "post_img": "",
                  "has_comments": True,
                  "comments" : [
                     {
                      "id": 1,
                      "user_fullname": "A person",
                      "time_ago": "14h",
                      'avatar_img': 'https://i.pravatar.cc/156',           
                      "message":  "This is a comment"
                     },
                   ],
                },
                { "id" : 3, 
                  "user_fullname" : "A friend" ,
                  'avatar_img': 'https://i.pravatar.cc/157',           
                  "timestamp" : "22 October 2021 at 20:28",
                  "message" : "Post without image",
                  "has_img" : False,
                  "post_img": "",
                  "has_comments": False,
                  "comments" : [],
                },
            ],
            }

@app.route('/')
def post():
    return render_template('post.html', vars=userdata, logo_img=logo_img)

@app.route('/form')
def form():
    return render_template('form.html')    

@app.route('/data/', methods = ['POST', 'GET'])
def data():
    if request.method == 'GET':
        return f"The URL /data is accessed directly. Try going to '/form' to submit form"
    if request.method == 'POST':
        form_data = request.form
        return render_template('data.html',form_data = form_data)
 
 
app.run(host='localhost', port=5000, debug=True)